<?php


namespace DH\EPGP\Views;


/**
 * Class TotalsView
 * @package Divine Heresy\EPGP\Views
 * @author Lucas Bradd <lucas@bradd.com.au>
 */
class TotalsView extends AbstractView
{
    /**
     * TotalsView constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->template = 'totals.twig';
        $this->characters = 'Test';
    }

    public function view()
    {
        $dummyData = [
            [
                "name" => "Bearskin",
                "class" => "Druid",
                "role" => "Tank",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 132,
                "gp" => 100,
                "pr" => 1.32,
            ],
            [
                "name" => "Beertanky",
                "class" => "Druid",
                "role" => "Tank",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 108,
                "gp" => 100,
                "pr" => 1.08,
            ],
            [
                "name" => "Belagorn",
                "class" => "Warrior",
                "role" => "Tank",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 100,
                "pr" => 1.52,
            ],
            [
                "name" => "Cais",
                "class" => "Rogue",
                "role" => "Melee",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 72,
                "gp" => 100,
                "pr" => 0.72,
            ],
            [
                "name" => "Carnifexus",
                "class" => "Mage",
                "role" => "Ranged",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 183,
                "pr" => 0.8306,
            ],
            [
                "name" => "Colomius",
                "class" => "Mage",
                "role" => "Ranged",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 108,
                "gp" => 135,
                "pr" => 0.8,
            ],
            [
                "name" => "Cornholio",
                "class" => "Druid",
                "role" => "Ranged",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 108,
                "gp" => 100,
                "pr" => 1.08,
            ],
            [
                "name" => "Danyen",
                "class" => "Priest",
                "role" => "Healer",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 108,
                "gp" => 100,
                "pr" => 1.08,
            ],
            [
                "name" => "Drdisco",
                "class" => "Shaman",
                "role" => "Melee",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 80,
                "gp" => 152,
                "pr" => 0.5263,
            ],
            [
                "name" => "Droody",
                "class" => "Druid",
                "role" => "Ranged",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 100,
                "pr" => 1.52,
            ],
            [
                "name" => "Fartalota",
                "class" => "Druid",
                "role" => "Healer",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 80,
                "gp" => 100,
                "pr" => 0.8,
            ],
            [
                "name" => "Grashak",
                "class" => "Hunter",
                "role" => "Ranged",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 128,
                "gp" => 100,
                "pr" => 1.28,
            ],
            [
                "name" => "Henchie",
                "class" => "Druid",
                "role" => "Healer",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 108,
                "gp" => 135,
                "pr" => 0.8,
            ],
            [
                "name" => "Hermes",
                "class" => "Druid",
                "role" => "Healer",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 60,
                "gp" => 100,
                "pr" => 0.6,
            ],
            [
                "name" => "Icecoldbro",
                "class" => "Mage",
                "role" => "Ranged",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 108,
                "gp" => 100,
                "pr" => 1.08,
            ],
            [
                "name" => "Jorna",
                "class" => "Priest",
                "role" => "Healer",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 100,
                "pr" => 1.52,
            ],
            [
                "name" => "Jug",
                "class" => "Warrior",
                "role" => "Melee",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 116,
                "gp" => 100,
                "pr" => 1.16,
            ],
            [
                "name" => "Kaytoo",
                "class" => "Priest",
                "role" => "Healer",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 135,
                "pr" => 1.1259,
            ],
            [
                "name" => "Krulz",
                "class" => "Warlock",
                "role" => "Ranged",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 56,
                "gp" => 100,
                "pr" => 0.56,
            ],
            [
                "name" => "Lgi",
                "class" => "Priest",
                "role" => "Healer",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 132,
                "gp" => 100,
                "pr" => 1.32,
            ],
            [
                "name" => "Maraina",
                "class" => "Druid",
                "role" => "Healer",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 108,
                "gp" => 152,
                "pr" => 0.7105,
            ],
            [
                "name" => "Mooherder",
                "class" => "Druid",
                "role" => "Healer",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 44,
                "gp" => 100,
                "pr" => 0.44,
            ],
            [
                "name" => "Moomighty",
                "class" => "Druid",
                "role" => "Healer",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 100,
                "pr" => 1.52,
            ],
            [
                "name" => "Moovurass",
                "class" => "Druid",
                "role" => "Healer",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 187,
                "pr" => 0.8128,
            ],
            [
                "name" => "NinetyNine",
                "class" => "Mage",
                "role" => "Ranged",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 103,
                "gp" => 100,
                "pr" => 1.03,
            ],
            [
                "name" => "Nitebabe",
                "class" => "Mage",
                "role" => "Ranged",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 44,
                "gp" => 100,
                "pr" => 0.44,
            ],
            [
                "name" => "Orcopalypse",
                "class" => "Warrior",
                "role" => "Tank",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 80,
                "gp" => 135,
                "pr" => 0.5926,
            ],
            [
                "name" => "Quake",
                "class" => "Warrior",
                "role" => "Tank",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 72,
                "gp" => 100,
                "pr" => 0.72,
            ],
            [
                "name" => "Ramster",
                "class" => "Hunter",
                "role" => "Ranged",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 135,
                "pr" => 1.1259,
            ],
            [
                "name" => "Roth",
                "class" => "Rogue",
                "role" => "Melee",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 100,
                "pr" => 1.52,
            ],
            [
                "name" => "Rummy",
                "class" => "Warrior",
                "role" => "Tank",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 100,
                "pr" => 1.52,
            ],
            [
                "name" => "Shadevar",
                "class" => "Rogue",
                "role" => "Melee",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 108,
                "gp" => 100,
                "pr" => 1.08,
            ],
            [
                "name" => "Shamer",
                "class" => "Shaman",
                "role" => "Healer",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 167,
                "pr" => 0.9102,
            ],
            [
                "name" => "Sinazaela",
                "class" => "Mage",
                "role" => "Ranged",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 44,
                "gp" => 100,
                "pr" => 0.44,
            ],
            [
                "name" => "Skiip",
                "class" => "Hunter",
                "role" => "Ranged",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 132,
                "gp" => 335,
                "pr" => 0.394,
            ],
            [
                "name" => "Smegoff",
                "class" => "Hunter",
                "role" => "Ranged",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 135,
                "pr" => 1.1259,
            ],
            [
                "name" => "Tabletopd",
                "class" => "Priest",
                "role" => "Healer",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 24,
                "gp" => 100,
                "pr" => 0.24,
            ],
            [
                "name" => "Taima",
                "class" => "Priest",
                "role" => "Healer",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 92,
                "gp" => 100,
                "pr" => 0.92,
            ],
            [
                "name" => "Tanksmun",
                "class" => "Warrior",
                "role" => "Tank",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 181,
                "pr" => 0.8398,
            ],
            [
                "name" => "Tehguns",
                "class" => "Shaman",
                "role" => "Melee",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 116,
                "gp" => 212,
                "pr" => 0.5472,
            ],
            [
                "name" => "Teracious",
                "class" => "Mage",
                "role" => "Ranged",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 152,
                "pr" => 1,
            ],
            [
                "name" => "Tronn",
                "class" => "Warlock",
                "role" => "Ranged",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 100,
                "pr" => 1.52,
            ],
            [
                "name" => "Unholymonk",
                "class" => "Warrior",
                "role" => "Melee",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 80,
                "gp" => 100,
                "pr" => 0.8,
            ],
            [
                "name" => "Unholysaph",
                "class" => "Priest",
                "role" => "Healer",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 201,
                "pr" => 0.7562,
            ],
            [
                "name" => "Volkuhn",
                "class" => "Warrior",
                "role" => "Melee",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 116,
                "gp" => 100,
                "pr" => 1.16,
            ],
            [
                "name" => "Winnieblue",
                "class" => "Priest",
                "role" => "Healer",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 100,
                "pr" => 1.52,
            ],
            [
                "name" => "Wizzjab",
                "class" => "Mage",
                "role" => "Ranged",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 20,
                "gp" => 100,
                "pr" => 0.2,
            ],
            [
                "name" => "Wotyournam",
                "class" => "Mage",
                "role" => "Ranged",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 100,
                "pr" => 1.52,
            ],
            [
                "name" => "Xelzenov",
                "class" => "Mage",
                "role" => "Ranged",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 100,
                "pr" => 1.52,
            ],
            [
                "name" => "Yag",
                "class" => "Warlock",
                "role" => "Ranged",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 133,
                "pr" => 1.1429,
            ],
            [
                "name" => "Zingerwork",
                "class" => "Warlock",
                "role" => "Ranged",
                "guild" => "Syzygy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 135,
                "pr" => 1.1259,
            ],
            [
                "name" => "Zurajita",
                "class" => "Warrior",
                "role" => "Melee",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 152,
                "gp" => 100,
                "pr" => 1.52,
            ],
            [
                "name" => "Tankyboi",
                "class" => "Warrior",
                "role" => "Melee",
                "guild" => "Divine Heresy",
                "lastRaid" => "22/07/2020 12:43",
                "ep" => 24,
                "gp" => 100,
                "pr" => 0.24,
            ],
        ];
        $this->twig->display($this->template, ['characters' => $dummyData]);
    }
}
